Repository reactiveui/refit, pull requests merged in 2021-02, with the labels that each got.

#1054 Hide generated types from IntelliSense
  InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
  Refit.Tests/InterfaceStubGenerator.cs
  Refit/UniqueName.cs
Labels: enhancement

#1055 Fix for multi template parameter use
  Refit.Tests/RequestBuilder.cs
  Refit/RestMethodInfo.cs
Labels: bug

#1047 Updated documentation for use of delegating handler with HttpClientFactory
  README.md
Labels: documentation

#1058 Prefix our local vars with ______ to prevent collisions
  InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
  Refit.Tests/InterfaceStubGenerator.cs
  Refit.Tests/RestService.cs
Labels: bug

#1060 Rename IContentSerializer to IHttpContentSerializer
  README.md
  Refit.Newtonsoft.Json/NewtonsoftJsonContentSerializer.cs
  Refit.Tests/MultipartTests.cs
  Refit.Tests/SerializedContentTests.cs
  Refit.Tests/XmlContentSerializerTests.cs
  Refit/ApiException.cs
  Refit/FormValueMultimap.cs
  Refit/JsonContentSerializer.cs
  Refit/RefitSettings.cs
  Refit/RequestBuilderImplementation.cs
  Refit/SystemTextJsonContentSerializer.cs
  Refit/XmlContentSerializer.cs
Labels: enhancement

#1062 Generate non-implicit impls for top-level interfaces
  InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
  Refit.Tests/InheritedInterfacesApi.cs
  Refit.Tests/InterfaceStubGenerator.cs
  Refit.Tests/RestService.cs
Labels: enhancement

#1067 Update output filenames to end in .g.cs to indicate they're generated.
  InterfaceStubGenerator.Core/InterfaceStubGenerator.cs
  Refit.Tests/InterfaceStubGenerator.cs
Labels: enhancement

#1086 Add error case for packages.config to prevent runtime issues
  README.md
  Refit/targets/refit.targets
Labels: enhancement

#1088 Update inferred types converter for 5.0
  Refit/SystemTextJsonContentSerializer.cs
Labels: bug
